// src/components/viewers/ViewerMsgpack.vue
<template>
  <JsonEditor ref='editor' :content='newContent' :readOnly='false'></JsonEditor>
</template>

<script type="text/javascript">
import JsonEditor from '@/components/JsonEditor';
import { decode, encode } from 'algo-msgpack-with-bigint';

import JSONbigFactory from '@qii404/json-bigint';
const JSONbig = JSONbigFactory({ useNativeBigInt: true });


export default {
  props: ['content'],
  components: { JsonEditor },
  computed: {
    newContent() {
      try {
        return decode(this.content);
      } catch (e) {
        return this.$t('message.msgpack_format_failed');
      }
    },
  },
  methods: {
    getContent() {
      let content = this.$refs.editor.getRawContent();

      // raw content is an object
      if (typeof this.newContent !== 'string') {
        try {
          content = JSONbig.parse(content);
        } catch (e) {
          // object parse failed
          this.$message.error({
            message: `Raw content is an object, but now parse object failed: ${e.message}`,
            duration: 6000,
          });

          return false;
        }
      }

      // encode returns Uint8Array
      return Buffer.from(encode(content));
    },
    copyContent() {
      const content = decode(this.content);
      return (typeof content === 'object') ? JSONbig.stringify(content) : content;
    },
  },
};
</script>

// src/components/viewers/ViewerMsgpack.tsx
'use client'

import { useMemo } from 'react'
import { decode } from 'algo-msgpack-with-bigint'
import { MonacoEditor } from '@/components/shared/MonacoEditor'

export function ViewerMsgpack({ value }: { value: Uint8Array }) {
  const { text, error } = useMemo(() => {
    try {
      const decoded = decode(value)
      return { text: JSON.stringify(decoded, null, 2), error: null }
    } catch (e) {
      return { text: null, error: e instanceof Error ? e.message : String(e) }
    }
  }, [value])

  if (error) {
    return (
      <div className="h-full w-full p-3">
        <div className="px-3 py-2 text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded">
          Msgpack decode failed: {error}
        </div>
      </div>
    )
  }

  return (
    <div className="h-full w-full">
      <MonacoEditor value={text ?? ''} language="json" readOnly />
    </div>
  )
}
